= Let's get Functional: The fast path to smart serverless with Spring Cloud Function & Azure Functions

== Maintainer

* Mark Heckler
* mailto:mark@thehecklers.com[mark@thehecklers.com]
* https://twitter.com/mkheck[@mkheck on Twitter]

== Purpose

This meta-repo accompanies my session titled *"Let's get Functional"* and includes all code written within the session and more. I'll update and add to these repos as the session evolves and/or as I think of more things to share.

*_Star+watch this repo (and linked repos) for updates!_*

== Notes

The PlaneFinder repo listed below pulls from a local aircraft tracking device I have in my home data center from PlaneFinder.net. If you don't have one and have no desire to host one, the PlaneFinder app generates sample data.

Both function repos below (_scf-af-aircraft-fn_ and _scf-af-position-fn_) have two branches, *scf* and *scfwithazurefunctions*. To run the Spring Cloud Function (SCF), be sure to checkout the *SCF* branch locally after fetching all branches. To execute locally or in Azure the version using SCF and Azure Functions, checkout the *scfwithazurefunctions* branch. Happy coding!

== Linked repos

* https://github.com/mkheck/scf-af-planefinder[PlaneFinder project: Spring Boot application]
* https://github.com/mkheck/scf-af-aircraft-fn[Aircraft project: Spring Cloud Function+Azure Functions)]
* https://github.com/mkheck/scf-af-position-fn[Aircraft Positions project: Spring Cloud Function+Azure Functions)]

== Related presentation

https://speakerdeck.com/mkheck/lets-get-functional["Let's get functional!" presentation]